---

- debug:
    msg: "Grafana DEB Repositories setup"

- name: add key
  apt_key:
    state: present
    url: https://packagecloud.io/gpg.key

- name: add repo
  template:
    src: grafana/grafana.deb.repo.j2
    dest: /etc/apt/sources.list.d/grafana_stable.list
