---

- debug:
    msg: "MongoDB DEB Repositories setup"


- name: add key
  apt_key:
    state: present
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6


- name: add repo
  template:
    src: mongodb/mongodb.deb.repo.j2
    dest: /etc/apt/sources.list.d/mongodb-3.4.list