---

- debug:
    msg: "MongoDB DEB Repositories setup"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: installed

- name: add key
  apt_key:
    state: present
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6


- name: add repo
  lineinfile:
    dest: /etc/apt/sources.list.d/mongodb-org-3.4.list
    create: yes
    line: 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/{{ansible_distribution|lower}} {{ansible_distribution_release}}/mongodb-org/3.4 multiverse'
