---

- debug:
    msg: "Jenkins DEB Repositories setup"

- name: add key
  apt_key:
    state: present
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key


- name: add repo
  template:
    src: jenkins/jenkins.deb.repo.j2
    dest: /etc/apt/sources.list.d/jenkins.list