---

- debug:
    msg: "Sublime Text DEB Repositories setup"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: installed

- name: add key
  apt_key:
    state: present
    url: https://download.sublimetext.com/sublimehq-pub.gpg

- name: add repo
  lineinfile:
    dest: /etc/apt/sources.list.d/sublime3.list
    create: yes
    line: 'deb https://download.sublimetext.com/ apt/stable/'
