#!/bin/bash
### BEGIN INIT INFO
# Provides:          colonizer
# Description:       Colonizer package manager.
# FALCON_BASE="/home/martin/falcon"
COLONIZER_BASE="/usr/local/colonizer"

COLONIZER_PACKAGES="$COLONIZER_BASE/packages"

function file_exists() {
    [ -f "$1" ]
}

# Root user detection
if [ $(echo "$UID") = "0" ]; then
    sudo_cmd=''
else
    sudo_cmd='sudo'
fi

action=$1

case $action in
        

    install)
        $0 update
        PLAYBOOK="$COLONIZER_PACKAGES/$2/main.yml"
        
        if file_exists $PLAYBOOK ; then
             $sudo_cmd sh -c "ansible-playbook $PLAYBOOK -i $COLONIZER_BASE/hosts"
        else
             printf "\033[31m \n Cant find a package named $2\n\033[0m\n"

        fi
        exit $?
        ;;


    update)
        $sudo_cmd sh -c "(cd $COLONIZER_BASE && git pull origin master)"
        exit $?
        ;;

    *)
        echo "Usage: $0 {install|update}"
        exit 2
        ;;
esac
