#!/bin/bash
### BEGIN INIT INFO
# Provides:          edgium
# Description:       Edgium package manager.
# FALCON_BASE="/home/martin/falcon"

EDGIUM_BASE="/usr/local/edgium"
EDGIUM_PACKAGES="$EDGIUM_BASE/packages"

function file_exists() {
    [ -f "$1" ]
}

# Root user detection
if [ $(echo "$UID") = "0" ]; then
    sudo_cmd=''
else
    sudo_cmd='sudo'
fi

action=$1

case $action in
        

    install)
        $0 update
        PLAYBOOK="$EDGIUM_PACKAGES/$2/main.yml"
        
        if file_exists $PLAYBOOK ; then
             $sudo_cmd sh -c "ansible-playbook $PLAYBOOK -i $EDGIUM_BASE/hosts"
        else
             printf "\033[31m \n Cant find a package named $2\n\033[0m\n"

        fi
        exit $?
        ;;


    update)
        $sudo_cmd sh -c "(cd $EDGIUM_BASE && git pull origin master)"
        exit $?
        ;;

    *)
        echo "Usage: $0 {install|update}"
        exit 2
        ;;
esac
