#!/bin/bash
### BEGIN INIT INFO
# Provides:          edgium
# Description:       Edgium package manager.
# FALCON_BASE="/home/martin/falcon"

EDGIUM_BASE="/usr/local/edgium"
EDGIUM_PACKAGES="$EDGIUM_BASE/apps"
AVAILABLE_PACKAGES=($(ls $EDGIUM_PACKAGES))

function file_exists() {
    [ -f "$1" ]
}

# Root user detection
if [ $(echo "$UID") = "0" ]; then
    sudo_cmd=''
else
    sudo_cmd='sudo'
fi

action=$1

function list_packages() {
   for value in "${AVAILABLE_PACKAGES[@]}"
   do
     printf "\033[33m  $value\n\033[0m"
   done 
}


case $action in
        

    install)
        $0 update
        PLAYBOOK="$EDGIUM_PACKAGES/$2/main.yml"
        
        if file_exists $PLAYBOOK ; then
             $sudo_cmd sh -c "ansible-playbook $PLAYBOOK -i $EDGIUM_BASE/hosts"
        else
             printf "\033[31m \n Can't find a package named $2\n\033[0m\n"
             printf "\033[42m  Available packages: \033[0m\n"
             list_packages

        fi
        exit $?
        ;;


    update)
        $sudo_cmd sh -c "(cd $EDGIUM_BASE && git pull origin master)"
        exit $?
        ;;

    *)
        echo "Usage: $0 {install|update}"
        exit 2
        ;;
esac
