---

- debug:
    msg: "Nginx DEB Repositories setup"

- name: add key
  apt_key:
    state: present
    url: https://nginx.org/keys/nginx_signing.key

- name: add repo
  template:
    src: nginx/nginx.deb.repo.j2
    dest: /etc/apt/sources.list.d/nginx.list
