---

- include: sublime-text/main.yml
  when: "'sublime-text' in devopsium_repositories"

- include: jenkins/main.yml
  when: "'jenkins' in devopsium_repositories"

- include: kubernetes/main.yml
  when: "'kubernetes' in devopsium_repositories"

- include: elasticsearch/main.yml
  when: "'elasticsearch' in devopsium_repositories"

- include: grafana/main.yml
  when: "'grafana' in devopsium_repositories"

- include: postgresql/main.yml
  when: "'postgresql' in devopsium_repositories"

- include: mongodb/main.yml
  when: "'mongodb' in devopsium_repositories"

- include: docker-ce/main.yml
  when: "'docker-ce' in devopsium_repositories"

- include: influxdb/main.yml
  when: "'influxdb' in devopsium_repositories"
