---

- include_tasks: deb_init.yml
  when: hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'

- include: "{{item}}/main.yml"
  with_items:
    - "{{devopsium_repositories}}"

- include_tasks: deb_update_cache.yml
  when: hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'