FROM edgium.ubuntu.14

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv AD53961F
RUN echo 'deb http://beta.packages.amon.cx/repo amon contrib' >> /etc/apt/sources.list
RUN apt-get update

RUN apt-get install -y --force-yes edgium

RUN edgium install boo

RUN apt-get remove -y edgium
RUN apt-get install -y --force-yes edgium


RUN apt-get remove -y edgium
RUN apt-get install -y --force-yes edgium

RUN edgium install boo

CMD ["/bin/bash"]