#! /bin/bash
PLUGINS_REPO=/usr/local/edgium
REMOTE_REPO=https://github.com/martinrusev/edgium.git

set -e

case "$1" in
    configure)

        rm -rf $PLUGINS_REPO
        git clone $REMOTE_REPO $PLUGINS_REPO
        
        set +e

    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
    ;;
esac

#DEBHELPER#

exit 0
