---

- debug:
    msg: "InfluxDB DEB Repositories setup"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: installed

- name: add key
  apt_key:
    state: present
    url: https://repos.influxdata.com/influxdb.key

# Works on both debian and ubuntu
- name: add repo
  lineinfile:
    dest: /etc/apt/sources.list.d/influxdb.list
    create: yes
    line: 'deb https://repos.influxdata.com/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable'
