---

- debug:
    msg: "InfluxDB DEB Repositories setup"


- name: add key
  apt_key:
    state: present
    url: https://repos.influxdata.com/influxdb.key


- name: add repo
  template:
    src: influxdb/influxdb.deb.repo.j2
    dest: /etc/apt/sources.list.d/influxdb.list