---
- hosts: localhost
  connection: local
  sudo: True
  vars:
    app: postgresql
    debian_list_file: /etc/apt/sources.list.d/edgium.{{app}}.list
  tasks:
    - include: debian_ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'