- name: Update.
  command: apt-get update

- name: Install dependecies.
  command: apt-get install -y --force-yes apt-transport-https

- name: Add Signing Key.
  apt_key: keyserver=keyserver.ubuntu.com id=36A1D7869245C8950F966E92D8576A8BA88D21E9 state=present

- name: Create list file
  lineinfile: dest={{debian_list_file}} regexp='^' line='' state=present create=True

- name: Add Repository.
  lineinfile: "dest={{debian_list_file}} line='deb https://get.docker.com/ubuntu docker main'"

- name: Update.
  command: apt-get update

- name: Install.
  command: apt-get install -y --force-yes lxc-docker

- shell: docker --version
  register: version

- debug: msg="{{version.stdout}}"