---

- debug:
    msg: "Docker CE DEB Repositories setup"

- name: add key
  apt_key:
    state: present
    url: https://download.docker.com/linux/ubuntu/gpg


- name: add repo
  template:
    src: docker-ce/docker-ce.deb.repo.j2
    dest: /etc/apt/sources.list.d/docker-ce.list
