---

- debug:
    msg: "PostgreSQL DEB Repositories setup"

- name: add key
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
    state: present

- name: add repo
  lineinfile: 
    create: yes 
    dest: /etc/apt/sources.list.d/postgresql.list
    line: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main'
