---

- debug:
    msg: "PostgreSQL DEB Repositories setup"


- name: add key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add repo
  template:
    src: postgresql/postgresql.deb.repo.j2
    dest: /etc/apt/sources.list.d/postgresql.list