---

- debug:
    msg: "ElasticSearch DEB Repositories setup"

- name: add key
  apt_key:
    state: present
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch


- name: cleanup existing repo
  file:
    dest: /etc/apt/sources.list.d/elastic-5.x.list
    state: absent

- name: add repo
  lineinfile:
    dest: /etc/apt/sources.list.d/elastic-5.x.list
    create: yes
    line: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
