---

- debug:
    msg: "ElasticSearch DEB Repositories setup"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: installed

- name: add key
  apt_key:
    state: present
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch


- name: add repo
  lineinfile:
    dest: /etc/apt/sources.list.d/elastic-5.x.list
    create: yes
    line: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
