---

- debug:
    msg: "VSCode DEB Repositories setup"


- name: add key
  apt_key:
    state: present
    url:  https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: add repo
  template:
    src: vscode/vscode.deb.repo.j2
    dest: /etc/apt/sources.list.d/vscode.list