---

- debug:
    msg: "VSCode DEB Repositories setup"

- name: install apt-transport-https
  apt:
    name: apt-transport-https
    state: installed

- name: add key
  apt_key:
    state: present
    url:  https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: add repo
  lineinfile:
    dest: /etc/apt/sources.list.d/vscode.list
    create: yes
    line: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
